export const restaurantData = [
  {
    id: "1",
    name: "Fradel And Spices",
    cuisine: "Italian",
    address: "123 Main St, CapeTown, WesternCape",
    priceRange: "R500 - R1000",
    tablePrice: 800,
    rating: 4.5,
    discription: `Welcome to Fradel And Spices, where culinary artistry meets a warm, inviting ambiance. Our restaurant is a haven for food enthusiasts, offering a diverse menu that takes your taste buds on a journey around the world. From mouthwatering steaks to delicate sushi rolls, our chefs craft each dish with precision and passion. The cozy, candlelit atmosphere provides the perfect setting for romantic dinners, family gatherings, or business meetings. Join us for an unforgettable dining experience that celebrates flavors, hospitality, and the joy of savoring exceptional cuisine`,
    image: require("./assets/images/restaurants/logo1.jpeg"),
  },
  {
    id: "2",
    name: "SavorCraze",
    cuisine: "Japanese",
    address: "456 Elm St, pretoria, Gauteng",
    priceRange: "R450 - R900",
    tablePrice: 800,
    discription: `Discover the essence of exquisite dining at 'SavorCraze,' where culinary artistry meets modern elegance. Our restaurant, nestled in the heart of the city, offers a diverse menu of delectable dishes prepared with the finest ingredients. From succulent steaks to fresh seafood and vegetarian delights, each plate is a masterpiece of flavor. Whether it's an intimate dinner or a gathering of friends, 'SavorCraze' provides a charming setting to savor unforgettable moments and exceptional cuisine`,
    rating: 4.0,
    image: require("./assets/images/restaurants/logo2.jpg"),
  },
  {
    id: "3",
    name: "Flavorsome Bites",
    cuisine: "Mexican",
    address: "789 Oak St, CapeTown, WesternCape",
    priceRange: "R300 - R800",
    tablePrice: 600,
    discription: `Welcome to Flavorsome Bites, where every dish is a journey of taste and every visit is a delightful experience. Our restaurant, located in a cozy corner of town, is your destination for mouthwatering cuisine. From savory starters to indulgent mains and heavenly desserts, our menu caters to all tastes. Whether you're dining for two or celebrating with a group, 'Flavorsome Bites' offers a warm and inviting ambiance, perfect for savoring exceptional flavors and creating lasting memories.`,
    rating: 3.8,
    image: require("./assets/images/restaurants/logo2.jpg"),
  },
  {
    id: "4",
    name: "Taste Haven",
    cuisine: "Mexican",
    address: "111 small St, joburg, Gauteng",
    priceRange: "R500 - R1000",
    tablePrice: 650,
    discription: `Step into 'Taste Haven,' your culinary escape in the heart of the city. Our restaurant is a fusion of flavors, offering a diverse menu to tantalize your taste buds. From savory classics to innovative creations, each dish is a celebration of taste. Whether you're seeking a romantic dinner or a casual gathering with friends, 'Taste Haven' provides a cozy and welcoming atmosphere where memorable moments are paired with exceptional cuisine`,
    rating: 3.8,
    image: require("./assets/images/restaurants/logo3.png"),
  },
  {
    id: "5",
    name: "Fradel And Spices",
    cuisine: "Italian",
    address: "123 Main St, Bloemfotein, FreeState",
    priceRange: "R500 - R1000",
    tablePrice: 800,
    discription: `Welcome to Fradel And Spices, where culinary artistry meets a warm, inviting ambiance. Our restaurant is a haven for food enthusiasts, offering a diverse menu that takes your taste buds on a journey around the world. From mouthwatering steaks to delicate sushi rolls, our chefs craft each dish with precision and passion. The cozy, candlelit atmosphere provides the perfect setting for romantic dinners, family gatherings, or business meetings. Join us for an unforgettable dining experience that celebrates flavors, hospitality, and the joy of savoring exceptional cuisine`,
    rating: 4.5,
    image: require("./assets/images/restaurants/logo1.jpeg"),
  },
  {
    id: "6",
    name: "SavorCraze 2",
    cuisine: "Japanese",
    address: "456 Elm St, pretoria, Gauteng",
    priceRange: "R450 - R900",
    tablePrice: 800,
    discription: `Discover the essence of exquisite dining at 'SavorCraze,' where culinary artistry meets modern elegance. Our restaurant, nestled in the heart of the city, offers a diverse menu of delectable dishes prepared with the finest ingredients. From succulent steaks to fresh seafood and vegetarian delights, each plate is a masterpiece of flavor. Whether it's an intimate dinner or a gathering of friends, 'SavorCraze' provides a charming setting to savor unforgettable moments and exceptional cuisine`,
    rating: 4.0,
    image: require("./assets/images/restaurants/logo2.jpg"),
  },
];

const database = {
  "2fWP8O6hVuQ9E2KxP3SfBtGTHp12": {
    userInfo: {
      date: "Thu Sep 28 2023 12:00:00 GMT+0200",
      guests: "5",
      name: "Khayo ",
      restaurant: "SavorCraze",
      restaurantAddress: "456 Elm St, pretoria, Gauteng",
      tablePrice: "R800",
      time: "17:00",
    },
  },
  DvZHv6QQjqTR9MErOQQuawDryPv1: {
    userInfo: {
      date: "Fri Sep 29 2023 12:00:00 GMT+0200",
      guests: "5",
      name: "kilo",
      restaurant: "Taste Haven",
      restaurantAddress: "111 small St, joburg, Gauteng",
      tablePrice: "R650",
      time: "17:00",
    },
  },
  WtxNQPsyUdOpDpvx498i1ExvWYu1: {
    userInfo: {
      date: "Fri Sep 22 2023 12:00:00 GMT+0200",
      guests: "5",
      name: "Pilo",
      restaurant: "Taste Haven",
      restaurantAddress: "111 small St, joburg, Gauteng",
      tablePrice: "R650",
      time: "17:00",
    },
  },
};
export default restaurantData;
